# Generated by Django 3.1.7 on 2021-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test Description of this product that you are viewing'),
            preserve_default=False,
        ),
    ]
